return {
  -- "nvim-lualine/lualine.nvim",
  -- event = "VeryLazy",
  -- init = function()
  --   vim.g.lualine_laststatus = vim.o.laststatus
  --   if vim.fn.argc(-1) > 0 then
  --     -- set an empty statusline till lualine loads
  --     vim.o.statusline = " "
  --   else
  --     -- hide the statusline on the starter page
  --     vim.o.laststatus = 0
  --   end
  -- end,
  -- opts = function()
  --   -- PERF: we don't need this lualine require madness 🤷
  --   local lualine_require = require("lualine_require")
  --   lualine_require.require = require
  --
  --   local icons = LazyVim.config.icons
  --
  --   vim.o.laststatus = vim.g.lualine_laststatus
  --
  --   local opts = {
  --     options = {
  --       theme = "auto",
  --       -- icons_enabled = true,
  --       globalstatus = vim.o.laststatus == 3,
  --       disabled_filetypes = { statusline = { "dashboard", "alpha", "ministarter", "snacks_dashboard" } },
  --       component_separators = "│",
  --       section_separators = "",
  --     },
  --     sections = {
  --       lualine_a = { "mode" },
  --       -- lualine_b = { "branch" },
  --
  --       lualine_b = {
  --         LazyVim.lualine.root_dir(),
  --         {
  --           "diagnostics",
  --           symbols = {
  --             error = icons.diagnostics.Error,
  --             warn = icons.diagnostics.Warn,
  --             info = icons.diagnostics.Info,
  --             hint = icons.diagnostics.Hint,
  --           },
  --         },
  --         { LazyVim.lualine.pretty_path() },
  --       },
  --       lualine_c = {},
  --       lualine_x = {
  --         Snacks.profiler.status(),
  --         -- stylua: ignore
  --         {
  --           function() return require("noice").api.status.command.get() end,
  --           cond = function() return package.loaded["noice"] and require("noice").api.status.command.has() end,
  --           color = function() return { fg = Snacks.util.color("Statement") } end,
  --         },
  --         -- stylua: ignore
  --         {
  --           function() return require("noice").api.status.mode.get() end,
  --           cond = function() return package.loaded["noice"] and require("noice").api.status.mode.has() end,
  --           color = function() return { fg = Snacks.util.color("Constant") } end,
  --         },
  --         -- stylua: ignore
  --         {
  --           function() return "  " .. require("dap").status() end,
  --           cond = function() return package.loaded["dap"] and require("dap").status() ~= "" end,
  --           color = function() return { fg = Snacks.util.color("Debug") } end,
  --         },
  --         -- stylua: ignore
  --         {
  --           require("lazy.status").updates,
  --           cond = require("lazy.status").has_updates,
  --           color = function() return { fg = Snacks.util.color("Special") } end,
  --         },
  --         {
  --           "diff",
  --           symbols = {
  --             added = icons.git.added,
  --             modified = icons.git.modified,
  --             removed = icons.git.removed,
  --           },
  --           source = function()
  --             local gitsigns = vim.b.gitsigns_status_dict
  --             if gitsigns then
  --               return {
  --                 added = gitsigns.added,
  --                 modified = gitsigns.changed,
  --                 removed = gitsigns.removed,
  --               }
  --             end
  --           end,
  --         },
  --       },
  --       lualine_y = {
  --         {
  --           function()
  --             return "󰚈 " .. "lines %L"
  --           end,
  --           separator = "",
  --         },
  --         { "location", separator = "" },
  --         { "copilot", show_colors = true },
  --         { "filetype", icon_only = false },
  --       },
  --       lualine_z = {
  --         -- function()
  --         --   return " " .. os.date("%R")
  --         -- end,
  --       },
  --     },
  --     extensions = { "neo-tree", "lazy", "fzf" },
  --   }
  --
  --   -- do not add trouble symbols if aerial is enabled
  --   -- And allow it to be overriden for some buffer types (see autocmds)
  --   if vim.g.trouble_lualine and LazyVim.has("trouble.nvim") then
  --     local trouble = require("trouble")
  --     local symbols = trouble.statusline({
  --       mode = "symbols",
  --       groups = {},
  --       title = false,
  --       filter = { range = true },
  --       format = "{kind_icon}{symbol.name:Normal}",
  --       hl_group = "lualine_c_normal",
  --     })
  --     table.insert(opts.sections.lualine_c, {
  --       symbols and symbols.get,
  --       cond = function()
  --         return vim.b.trouble_lualine ~= false and symbols.has()
  --       end,
  --     })
  --   end
  --
  --   -- 🔽🔽 add the copilot status component here (your snippet)
  --   table.insert(
  --     opts.sections.lualine_x,
  --     3,
  --     LazyVim.lualine.status("", function()
  --       local clients = package.loaded["copilot"] and LazyVim.lsp.get_clients({ name = "copilot", bufnr = 0 }) or {}
  --       if #clients > 0 then
  --         local status = require("copilot.api").status.data.status
  --         return (status == "InProgress" and "pending") or (status == "Warning" and "error") or "ok"
  --       end
  --     end)
  --   )
  --   -- 🔼🔼 end insert
  --
  --   return opts
  -- end,
}
